spring:
  profiles:
    active: dev
  application:
    name: spring-hotel
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: Hikari
      auto-commit: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${DEFAULT_SCHEMA}
  liquibase:
    contexts: dev
    change-log: classpath:db/changelog/master.xml
    default-schema: ${DEFAULT_SCHEMA}
    enabled: true
server:
  port: 8181
okta:
  oauth2:
    issuer: ${AUTH0_ISSUER}
    client-id: ${AUTH0_CLIENT_ID}
    client-secret: ${AUTH0_CLIENT_SECRET}
application:
  auth0:
    role-landlord-id: ${AUTH0_ROLE_LANDLORD}
logging:
  level:
    ROOT: INFO
    org.hibernate: INFO
    com.abimulia.hotel: DEBUG